export const SECTION_TYPE_LABELS: Record<string, string> = {
  Hero: "Bosh banner",
  TrustBar: "Ishonch paneli",
  Stats: "Statistika",
  Features: "Nega biz",
  Comparison: "Qiyoslash",
  Products: "Mahsulotlar",
  PrivateLabel: "Private Label",
  Process: "Jarayon",
  Quality: "Sifat",
  Partners: "Hamkorlar",
  CTA: "Chaqiriq (CTA)",
  About: "Kompaniya haqida",
  Certificates: "Sertifikatlar",
  Contact: "Aloqa",
  WhyPartner: "Nega hamkor bo'lish",
  WhoWeWorkWith: "Kimlar bilan ishlaymiz",
  ProductRange: "Mahsulot assortimenti",
  ExportCapabilities: "Eksport imkoniyatlari",
  Gallery: "Galereya",
  FAQ: "Savol-javoblar",
  CategoryTabs: "Kategoriya tablari",
  PageBanner: "Sahifa banneri",
  BackgroundHero: "Fon-rasmli banner",
  StatsHero: "Statistikali banner",
  MinimalHero: "Minimal banner",
  BadgeListHero: "Belgilar bilan banner",
  BreadcrumbHero: "Breadcrumb banner",
  QualityIconGrid: "Sifat — ikonka grid",
  QualityMetrics: "Sifat — ko'rsatkichlar",
  QualityChecklist: "Sifat — nazorat ro'yxati",
  QualityBadgeWall: "Sifat — sertifikat devori",
  QualityPledge: "Sifat — va'da",
  ProcessTimelineVertical: "Jarayon — vertikal timeline",
  ProcessCardGrid: "Jarayon — rasmli kartalar",
  ProcessSplitImage: "Jarayon — rasm va bosqichlar",
  ProcessFlow: "Jarayon — ikonka oqimi",
  ProcessAccordion: "Jarayon — ochiladigan ro'yxat",
  WhyPartnerIconGrid: "Nega hamkor — ikonka grid",
  WhyPartnerMetrics: "Nega hamkor — ko'rsatkichlar",
  WhyPartnerSplitImage: "Nega hamkor — rasm va ro'yxat",
  WhyPartnerQuote: "Nega hamkor — sharh",
  WhyPartnerCtaBand: "Nega hamkor — chaqiriq banneri",
};

export function sectionTypeLabel(typeName: string): string {
  return SECTION_TYPE_LABELS[typeName] ?? typeName;
}
