import type { RepeaterFieldDef } from "../../../components/admin/RepeaterEditor";
import { BG_VARIANT_FIELD } from "../../../lib/utils/sectionBgVariant";

export type FieldType = "text" | "textarea" | "stringlist" | "repeater" | "image" | "pagelink" | "select" | "file";

export interface FieldDef {
  key: string;
  label: string;
  type: FieldType;
  hint?: string;
  itemFields?: RepeaterFieldDef[];
  itemLabel?: string;
  options?: { value: string; label: string }[];
}

export const SECTION_FIELD_SCHEMAS: Record<string, FieldDef[]> = {
  Hero: [
    { key: "breadcrumbHome", label: "Breadcrumb: Bosh sahifa matni", type: "text" },
    { key: "breadcrumbCurrent", label: "Breadcrumb: Joriy sahifa matni", type: "text" },
    { key: "badge", label: "Badge matni", type: "text" },
    { key: "title", label: "Sarlavha", type: "text" },
    { key: "highlight", label: "Sarlavhadagi ajratilgan qism (yashil)", type: "text" },
    { key: "subtitle", label: "Tasvir matni", type: "textarea" },
    { key: "primaryButtonText", label: "Asosiy tugma matni", type: "text" },
    { key: "primaryButtonUrl", label: "Asosiy tugma havolasi", type: "text" },
    { key: "secondaryButtonText", label: "Ikkinchi tugma matni", type: "text" },
    { key: "secondaryButtonUrl", label: "Ikkinchi tugma havolasi", type: "text" },
    { key: "imageUrl", label: "Rasm", type: "image" },
    {
      key: "imageStats",
      label: "Rasm ustidagi statistika",
      type: "repeater",
      itemLabel: "Statistika",
      itemFields: [
        { key: "value", label: "Qiymat" },
        { key: "label", label: "Yorlik" },
      ],
    },
    { key: "checklist", label: "Belgilar ro'yxati", type: "stringlist" },
  ],
  TrustBar: [
    { key: "eyebrow", label: "Eyebrow matni", type: "text" },
    { key: "badges", label: "Sertifikat belgilari", type: "stringlist" },
    { key: "highlight", label: "Oxirgi ajratilgan matn", type: "text" },
  ],
  Stats: [
    {
      key: "items",
      label: "Statistika kartalari",
      type: "repeater",
      itemLabel: "Karta",
      hint: "icon: factory, globe, badge, box",
      itemFields: [
        { key: "icon", label: "Ikon (factory/globe/badge/box)" },
        { key: "value", label: "Qiymat" },
        { key: "label", label: "Yorlik" },
      ],
    },
  ],
  Features: [
    { key: "eyebrow", label: "Eyebrow matni", type: "text" },
    { key: "title", label: "Sarlavha", type: "text" },
    { key: "subtitle", label: "Matn", type: "textarea" },
  ],
  Comparison: [
    BG_VARIANT_FIELD,
    { key: "eyebrow", label: "Eyebrow matni", type: "text" },
    { key: "title", label: "Sarlavha", type: "text" },
    { key: "subtitle", label: "Matn", type: "textarea" },
    { key: "leftLabel", label: "Chap ustun nomi", type: "text" },
    { key: "leftTitle", label: "Chap ustun sarlavhasi", type: "text" },
    { key: "leftItems", label: "Chap ustun bandlari", type: "stringlist" },
    { key: "rightBadge", label: "O'ng ustun belgisi", type: "text" },
    { key: "rightLabel", label: "O'ng ustun nomi", type: "text" },
    { key: "rightTitle", label: "O'ng ustun sarlavhasi", type: "text" },
    { key: "rightItems", label: "O'ng ustun bandlari", type: "stringlist" },
  ],
  Products: [
    { key: "eyebrow", label: "Eyebrow matni", type: "text" },
    { key: "title", label: "Sarlavha", type: "text" },
    { key: "subtitle", label: "Matn", type: "textarea" },
    { key: "buttonText", label: "Tugma matni", type: "text" },
    { key: "buttonUrl", label: "Tugma havolasi", type: "text" },
  ],
  PrivateLabel: [
    { key: "eyebrow", label: "Eyebrow matni", type: "text" },
    { key: "title", label: "Sarlavha", type: "text" },
    { key: "subtitle", label: "Matn", type: "textarea" },
    {
      key: "steps",
      label: "Bosqichlar",
      type: "repeater",
      itemLabel: "Bosqich",
      itemFields: [
        { key: "number", label: "Raqam" },
        { key: "label", label: "Nomi" },
        { key: "title", label: "Sarlavha (ixtiyoriy)" },
        { key: "description", label: "Tavsif", type: "textarea" },
        { key: "icon", label: "Ikon (formula/packaging/quality/export)" },
      ],
    },
    { key: "buttonText", label: "Tugma matni", type: "text" },
    { key: "buttonUrl", label: "Tugma havolasi", type: "text" },
    { key: "ctaTitle", label: "CTA sarlavhasi", type: "text" },
    { key: "ctaSubtitle", label: "CTA matni", type: "textarea" },
  ],
  Process: [
    { key: "eyebrow", label: "Eyebrow matni", type: "text" },
    { key: "title", label: "Sarlavha", type: "text" },
    { key: "subtitle", label: "Matn", type: "textarea" },
    {
      key: "steps",
      label: "Bosqichlar",
      type: "repeater",
      itemLabel: "Bosqich",
      itemFields: [
        { key: "number", label: "Raqam" },
        { key: "title", label: "Sarlavha" },
        { key: "description", label: "Tavsif", type: "textarea" },
        { key: "icon", label: "Ikon (inquiry/agreement/export/wheat/formula/factory/quality/packaging/shipping)" },
      ],
    },
    { key: "buttonText", label: "Tugma matni", type: "text" },
    { key: "buttonUrl", label: "Tugma havolasi", type: "text" },
    { key: "ctaTitle", label: "CTA sarlavhasi", type: "text" },
    { key: "ctaSubtitle", label: "CTA matni", type: "textarea" },
  ],
  Quality: [
    { key: "eyebrow", label: "Eyebrow matni", type: "text" },
    { key: "title", label: "Sarlavha", type: "text" },
    { key: "subtitle", label: "Matn", type: "textarea" },
    { key: "items", label: "Bandlar", type: "stringlist" },
    { key: "imageUrl", label: "Rasm", type: "image" },
  ],
  Partners: [
    { key: "eyebrow", label: "Eyebrow matni", type: "text" },
    { key: "title", label: "Sarlavha", type: "text" },
    { key: "subtitle", label: "Matn", type: "textarea" },
    {
      key: "cards",
      label: "Kartalar",
      type: "repeater",
      itemLabel: "Karta",
      hint: "icon: globe, factory, shield, package",
      itemFields: [
        { key: "icon", label: "Ikon (globe/factory/shield/package)" },
        { key: "title", label: "Sarlavha" },
        { key: "description", label: "Tavsif", type: "textarea" },
      ],
    },
  ],
  CTA: [
    BG_VARIANT_FIELD,
    { key: "title", label: "Sarlavha (boshlanishi)", type: "text" },
    { key: "highlight", label: "Ajratilgan qism", type: "text" },
    { key: "titleEnd", label: "Sarlavha (davomi)", type: "text" },
    { key: "subtitle", label: "Matn", type: "textarea" },
    { key: "buttonText", label: "Tugma matni", type: "text" },
    { key: "buttonUrl", label: "Tugma havolasi", type: "file", hint: "Ichki sahifa yo'li (masalan /contact), yuklangan fayl (PDF), yoki \"certificates\" — sertifikatlar ro'yxati oynasini ochadi" },
    { key: "secondaryButtonText", label: "2-tugma matni", type: "text" },
    { key: "secondaryButtonUrl", label: "2-tugma havolasi", type: "file", hint: "Ichki sahifa yo'li (masalan /contact), yuklangan fayl (PDF), yoki \"certificates\" — sertifikatlar ro'yxati oynasini ochadi" },
  ],
  About: [
    { key: "title", label: "Sarlavha", type: "text" },
    { key: "subtitle", label: "Kichik sarlavha", type: "text" },
    { key: "content", label: "Matn", type: "textarea" },
    { key: "buttonText", label: "Tugma matni", type: "text" },
    { key: "buttonUrl", label: "Tugma havolasi", type: "text" },
    { key: "imageUrl", label: "Rasm", type: "image" },
  ],
  Certificates: [
    { key: "title", label: "Sarlavha", type: "text" },
    { key: "subtitle", label: "Kichik sarlavha", type: "text" },
    { key: "content", label: "Matn", type: "textarea" },
    { key: "imageUrl", label: "Rasm (yagona, ixtiyoriy)", type: "image" },
    {
      key: "items",
      label: "Sertifikatlar to'plami",
      type: "repeater",
      itemLabel: "Sertifikat",
      itemFields: [
        { key: "imageUrl", label: "Rasm", type: "image" },
        { key: "name", label: "Nomi" },
        { key: "downloadUrl", label: "PDF havolasi (bo'lsa, rasm o'rniga yuklab olish tugmasi ko'rsatiladi)" },
      ],
    },
  ],
  Contact: [
    { key: "title", label: "Sarlavha", type: "text" },
    { key: "subtitle", label: "Kichik sarlavha", type: "text" },
    { key: "content", label: "Matn", type: "textarea" },
    { key: "buttonText", label: "Tugma matni", type: "text" },
    { key: "buttonUrl", label: "Tugma havolasi", type: "text" },
  ],
  WhyPartner: [
    { key: "eyebrow", label: "Eyebrow matni", type: "text" },
    { key: "title", label: "Sarlavha", type: "text" },
    { key: "subtitle", label: "Matn", type: "textarea" },
    {
      key: "cards",
      label: "Kartalar",
      type: "repeater",
      itemLabel: "Karta",
      hint: "icon: factory, globe, badge, box, truck, shield, handshake, document, chart, support, store, warehouse",
      itemFields: [
        { key: "icon", label: "Ikon" },
        { key: "title", label: "Sarlavha" },
        { key: "description", label: "Tavsif", type: "textarea" },
      ],
    },
    { key: "imageUrl", label: "Rasm", type: "image" },
  ],
  WhoWeWorkWith: [
    { key: "eyebrow", label: "Eyebrow matni", type: "text" },
    { key: "title", label: "Sarlavha", type: "text" },
    { key: "subtitle", label: "Matn", type: "textarea" },
    {
      key: "cards",
      label: "Hamkor turlari",
      type: "repeater",
      itemLabel: "Hamkor turi",
      itemFields: [
        { key: "icon", label: "Ikon" },
        { key: "title", label: "Sarlavha" },
        { key: "description", label: "Tavsif", type: "textarea" },
      ],
    },
    { key: "imageUrl", label: "Rasm", type: "image" },
  ],
  ExportCapabilities: [
    { key: "flag", label: "Bayroq (emoji)", type: "text", hint: "Masalan: 🇧🇪" },
    { key: "title", label: "Sarlavha", type: "text" },
    { key: "subtitle", label: "Tasvir matni", type: "textarea" },
    {
      key: "logos",
      label: "Sertifikat logotiplari",
      type: "repeater",
      itemLabel: "Logotip",
      itemFields: [
        { key: "imageUrl", label: "Rasm", type: "image" },
        { key: "name", label: "Nomi" },
      ],
    },
  ],
  ProductRange: [
    { key: "eyebrow", label: "Eyebrow matni", type: "text" },
    { key: "title", label: "Sarlavha", type: "text" },
    { key: "subtitle", label: "Matn", type: "textarea" },
    {
      key: "categorySlugs",
      label: "Ko'rsatiladigan toifalar (slug)",
      type: "stringlist",
      hint: "Bo'sh qoldirilsa barcha faol toifalar ko'rsatiladi",
    },
  ],
  Gallery: [
    BG_VARIANT_FIELD,
    { key: "eyebrow", label: "Eyebrow matni", type: "text" },
    { key: "title", label: "Sarlavha", type: "text" },
    {
      key: "images",
      label: "Rasmlar",
      type: "repeater",
      itemLabel: "Rasm",
      itemFields: [
        { key: "imageUrl", label: "Rasm", type: "image" },
        { key: "category", label: "Toifa (masalan: Ishlab chiqarish)" },
        { key: "caption", label: "Izoh" },
      ],
    },
  ],
  FAQ: [
    BG_VARIANT_FIELD,
    { key: "eyebrow", label: "Eyebrow matni", type: "text" },
    { key: "title", label: "Sarlavha", type: "text" },
    {
      key: "items",
      label: "Savol-javoblar",
      type: "repeater",
      itemLabel: "Savol",
      itemFields: [
        { key: "question", label: "Savol" },
        { key: "answer", label: "Javob", type: "textarea" },
      ],
    },
  ],
  PageBanner: [
    { key: "eyebrow", label: "Eyebrow matni", type: "text" },
    { key: "title", label: "Sarlavha", type: "text" },
    { key: "highlight", label: "Sarlavhadagi ajratilgan qism (yashil, yangi qatorda)", type: "text" },
    { key: "subtitle", label: "Tasvir matni", type: "textarea" },
    { key: "primaryButtonText", label: "Asosiy tugma matni", type: "text" },
    { key: "primaryButtonUrl", label: "Asosiy tugma havolasi", type: "text" },
    { key: "secondaryButtonText", label: "Ikkinchi tugma matni", type: "text" },
    { key: "secondaryButtonUrl", label: "Ikkinchi tugma havolasi", type: "text" },
    { key: "imageUrl", label: "Rasm (ixtiyoriy)", type: "image" },
  ],
  BackgroundHero: [
    {
      key: "contentAlign",
      label: "Matn joylashuvi",
      type: "select",
      options: [
        { value: "left", label: "Chapda" },
        { value: "center", label: "Markazda" },
      ],
    },
    { key: "eyebrow", label: "Eyebrow matni", type: "text" },
    { key: "title", label: "Sarlavha", type: "text" },
    { key: "subtitle", label: "Tasvir matni", type: "textarea" },
    { key: "buttonText", label: "1-tugma matni", type: "text" },
    { key: "buttonUrl", label: "1-tugma havolasi", type: "pagelink" },
    { key: "buttonText2", label: "2-tugma matni", type: "text" },
    { key: "buttonUrl2", label: "2-tugma havolasi", type: "pagelink" },
    { key: "backgroundImageUrl", label: "Fon rasmi", type: "image" },
  ],
  StatsHero: [
    { key: "eyebrow", label: "Eyebrow matni", type: "text" },
    { key: "title", label: "Sarlavha", type: "text" },
    { key: "subtitle", label: "Tasvir matni", type: "textarea" },
    { key: "buttonText", label: "Tugma matni", type: "text" },
    { key: "buttonUrl", label: "Tugma havolasi", type: "text" },
    {
      key: "stats",
      label: "Statistika qatori",
      type: "repeater",
      itemLabel: "Statistika",
      itemFields: [
        { key: "value", label: "Qiymat" },
        { key: "label", label: "Yorlik" },
      ],
    },
  ],
  MinimalHero: [
    { key: "eyebrow", label: "Eyebrow matni", type: "text" },
    { key: "title", label: "Sarlavha", type: "text" },
    { key: "subtitle", label: "Tasvir matni", type: "textarea" },
    { key: "buttonText", label: "Tugma matni", type: "text" },
    { key: "buttonUrl", label: "Tugma havolasi", type: "text" },
  ],
  BadgeListHero: [
    { key: "eyebrow", label: "Eyebrow matni", type: "text" },
    { key: "title", label: "Sarlavha", type: "text" },
    { key: "subtitle", label: "Tasvir matni", type: "textarea" },
    { key: "buttonText", label: "Tugma matni", type: "text" },
    { key: "buttonUrl", label: "Tugma havolasi", type: "text" },
    { key: "checklist", label: "Belgilar ro'yxati", type: "stringlist" },
    { key: "imageUrl", label: "Rasm", type: "image" },
  ],
  BreadcrumbHero: [
    { key: "breadcrumbHome", label: "Breadcrumb: Bosh sahifa matni", type: "text" },
    { key: "breadcrumbCurrent", label: "Breadcrumb: Joriy sahifa matni", type: "text" },
    { key: "title", label: "Sarlavha", type: "text" },
    { key: "subtitle", label: "Tasvir matni", type: "textarea" },
  ],
  // Tabs (Ingredientlar / Itlar-Mushuklar uchun / Zavodchilarga / Qayerdan
  // sotib olish) are derived automatically from the category slug — no
  // editable fields, and no risk of a page ending up with a stale tab list.
  CategoryTabs: [],
  QualityIconGrid: [
    BG_VARIANT_FIELD,
    { key: "eyebrow", label: "Eyebrow matni", type: "text" },
    { key: "title", label: "Sarlavha", type: "text" },
    { key: "subtitle", label: "Tasvir matni", type: "textarea" },
    {
      key: "items",
      label: "Sifat mezonlari",
      type: "repeater",
      itemLabel: "Mezon",
      itemFields: [
        { key: "icon", label: "Ikonka (shield/badge/award/leaf/beaker/sparkles)" },
        { key: "title", label: "Sarlavha" },
        { key: "description", label: "Tavsif", type: "textarea" },
      ],
    },
    { key: "warningText", label: "Ogohlantirish matni (ixtiyoriy)", type: "textarea" },
  ],
  QualityMetrics: [
    BG_VARIANT_FIELD,
    { key: "eyebrow", label: "Eyebrow matni", type: "text" },
    {
      key: "badgeTone",
      label: "Eyebrow rangi",
      type: "select",
      options: [
        { value: "default", label: "Standart (yashil)" },
        { value: "warm", label: "Iliq (jigarrang)" },
      ],
    },
    { key: "title", label: "Sarlavha", type: "text" },
    {
      key: "titleIcon",
      label: "Sarlavha ikonkasi",
      type: "select",
      options: [
        { value: "", label: "Yo'q" },
        { value: "dog", label: "It" },
        { value: "cat", label: "Mushuk" },
      ],
    },
    { key: "subtitle", label: "Tasvir matni", type: "textarea" },
    {
      key: "columns",
      label: "Panjara ustunlari",
      type: "select",
      options: [
        { value: "5", label: "5 ustunli qator" },
        { value: "3", label: "3 ustunli (2 qator)" },
      ],
    },
    {
      key: "metrics",
      label: "Ko'rsatkichlar",
      type: "repeater",
      itemLabel: "Ko'rsatkich",
      itemFields: [
        { key: "value", label: "Qiymat" },
        { key: "label", label: "Yorlik" },
      ],
    },
  ],
  QualityChecklist: [
    { key: "eyebrow", label: "Eyebrow matni", type: "text" },
    { key: "title", label: "Sarlavha", type: "text" },
    { key: "subtitle", label: "Tasvir matni", type: "textarea" },
    { key: "imageUrl", label: "Rasm", type: "image" },
    { key: "checklist", label: "Nazorat ro'yxati (raqamlangan)", type: "stringlist" },
    { key: "buttonText", label: "Tugma matni", type: "text" },
    { key: "buttonUrl", label: "Tugma havolasi", type: "text" },
  ],
  QualityBadgeWall: [
    { key: "eyebrow", label: "Eyebrow matni", type: "text" },
    { key: "title", label: "Sarlavha", type: "text" },
    { key: "subtitle", label: "Tasvir matni", type: "textarea" },
    {
      key: "badges",
      label: "Sertifikatlar",
      type: "repeater",
      itemLabel: "Sertifikat",
      itemFields: [
        { key: "icon", label: "Ikonka (shield/badge/award/document/seal)" },
        { key: "title", label: "Nomi" },
        { key: "description", label: "Beruvchi tashkilot" },
      ],
    },
  ],
  QualityPledge: [
    { key: "quote", label: "Va'da matni", type: "textarea" },
    { key: "author", label: "Muallif", type: "text" },
    { key: "role", label: "Lavozimi", type: "text" },
  ],
  ProcessTimelineVertical: [
    BG_VARIANT_FIELD,
    { key: "eyebrow", label: "Eyebrow matni", type: "text" },
    { key: "title", label: "Sarlavha", type: "text" },
    { key: "subtitle", label: "Tasvir matni", type: "textarea" },
    {
      key: "steps",
      label: "Bosqichlar",
      type: "repeater",
      itemLabel: "Bosqich",
      itemFields: [
        { key: "title", label: "Sarlavha" },
        { key: "description", label: "Tavsif", type: "textarea" },
      ],
    },
  ],
  ProcessCardGrid: [
    { key: "eyebrow", label: "Eyebrow matni", type: "text" },
    { key: "title", label: "Sarlavha", type: "text" },
    { key: "subtitle", label: "Tasvir matni", type: "textarea" },
    {
      key: "steps",
      label: "Bosqichlar",
      type: "repeater",
      itemLabel: "Bosqich",
      itemFields: [
        { key: "title", label: "Sarlavha" },
        { key: "description", label: "Tavsif", type: "textarea" },
        { key: "imageUrl", label: "Rasm", type: "image" },
      ],
    },
  ],
  ProcessSplitImage: [
    BG_VARIANT_FIELD,
    { key: "eyebrow", label: "Eyebrow matni", type: "text" },
    { key: "title", label: "Sarlavha", type: "text" },
    { key: "subtitle", label: "Tasvir matni", type: "textarea" },
    { key: "imageUrl", label: "Rasm", type: "image" },
    {
      key: "steps",
      label: "Bosqichlar",
      type: "repeater",
      itemLabel: "Bosqich",
      itemFields: [
        { key: "title", label: "Sarlavha" },
        { key: "description", label: "Tavsif", type: "textarea" },
      ],
    },
  ],
  ProcessFlow: [
    { key: "eyebrow", label: "Eyebrow matni", type: "text" },
    { key: "title", label: "Sarlavha", type: "text" },
    { key: "subtitle", label: "Tasvir matni", type: "textarea" },
    {
      key: "steps",
      label: "Bosqichlar",
      type: "repeater",
      itemLabel: "Bosqich",
      itemFields: [
        { key: "icon", label: "Ikonka (inquiry/agreement/quality/packaging/shipping)" },
        { key: "title", label: "Sarlavha" },
      ],
    },
  ],
  ProcessAccordion: [
    { key: "eyebrow", label: "Eyebrow matni", type: "text" },
    { key: "title", label: "Sarlavha", type: "text" },
    { key: "subtitle", label: "Tasvir matni", type: "textarea" },
    {
      key: "steps",
      label: "Bosqichlar",
      type: "repeater",
      itemLabel: "Bosqich",
      itemFields: [
        { key: "title", label: "Sarlavha" },
        { key: "description", label: "Tavsif", type: "textarea" },
      ],
    },
  ],
  WhyPartnerIconGrid: [
    { key: "eyebrow", label: "Eyebrow matni", type: "text" },
    { key: "title", label: "Sarlavha", type: "text" },
    { key: "subtitle", label: "Tasvir matni", type: "textarea" },
    {
      key: "items",
      label: "Afzalliklar",
      type: "repeater",
      itemLabel: "Afzallik",
      itemFields: [
        { key: "icon", label: "Ikonka (handshake/globe/shield/truck/package/trending)" },
        { key: "title", label: "Sarlavha" },
        { key: "description", label: "Tavsif", type: "textarea" },
      ],
    },
  ],
  WhyPartnerMetrics: [
    { key: "eyebrow", label: "Eyebrow matni", type: "text" },
    { key: "title", label: "Sarlavha", type: "text" },
    { key: "subtitle", label: "Tasvir matni", type: "textarea" },
    {
      key: "metrics",
      label: "Ko'rsatkichlar",
      type: "repeater",
      itemLabel: "Ko'rsatkich",
      itemFields: [
        { key: "value", label: "Qiymat" },
        { key: "label", label: "Yorlik" },
      ],
    },
  ],
  WhyPartnerSplitImage: [
    { key: "eyebrow", label: "Eyebrow matni", type: "text" },
    { key: "title", label: "Sarlavha", type: "text" },
    { key: "subtitle", label: "Tasvir matni", type: "textarea" },
    { key: "imageUrl", label: "Rasm", type: "image" },
    { key: "checklist", label: "Afzalliklar ro'yxati", type: "stringlist" },
    { key: "buttonText", label: "Tugma matni", type: "text" },
    { key: "buttonUrl", label: "Tugma havolasi", type: "text" },
  ],
  WhyPartnerQuote: [
    { key: "quote", label: "Sharh matni", type: "textarea" },
    { key: "author", label: "Muallif", type: "text" },
    { key: "role", label: "Lavozimi / kompaniyasi", type: "text" },
    { key: "avatarUrl", label: "Rasm (ixtiyoriy)", type: "image" },
  ],
  WhyPartnerCtaBand: [
    { key: "title", label: "Sarlavha", type: "text" },
    { key: "subtitle", label: "Tasvir matni", type: "textarea" },
    { key: "checklist", label: "Afzalliklar ro'yxati", type: "stringlist" },
    { key: "buttonText", label: "Tugma matni", type: "text" },
    { key: "buttonUrl", label: "Tugma havolasi", type: "text" },
  ],
};
